### ISSUE TITLE
Linux sug: mention that root is required

### ISSUE THREAD

**Issue by edrozenberg** [rmull/tinkup#3]
Thanks for this useful tool! Just updated my RT 5x and it worked great.

A small sug to mention in the readme that on Linux it requires using the root user in many/most cases, unless the user already has permissions on the relevant serial/USB tty device.

A regular non-root user without the required permissions would see something similar to the following:
```
Could not open device at /dev/ttyUSB0
Exception: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
```

Probably close to 100% of the users who will do this on Linux can already figure this out on their own :).

**Comment by rmull** [comment]
I added some notes about this to the README - thank you for the suggestion.

**Comment by edrozenberg** [comment]
Looks great thanks! Pretty sure reboot is not required (though that certainly works) - only requires user logs out and back in, so that the new group membership is read by the shell.

"sudo usermod -a -G dialout youruser, then rebooting" -> 
"sudo usermod -a -G dialout youruser, then logging out and logging back in, or rebooting."

**Comment by rmull** [comment]
I agree that logout is sufficient. I'm trying to keep the instructions simple at expense of precision, since there are already too many words. Rebooting will certainly cover the bases, since beginners can be confused about whether they are actually completely logged out in some cases, and power users will know what they need to do. Though I'm leaving it as-is, I appreciate the discussion/feedback.

**Comment by edrozenberg** [comment]
Completely makes sense. "What do you mean logout, what logs, I don't know where logs are. Is it my login shell, what? Interact what shell? Screen or tmux, t what?"
